<?php 
/*
Plugin Name: CardCom - Elementor Forms Integration
Plugin URI: https://yarinayash.com/cardcom-elementor-forms-integration
Description: CardCom - Elementor Forms Integration
Version: 0.0.1
Author: Yarin Ayash
Author URI: https://yarinayash.com
Text Domain: cefi
Generated By: http://ensuredomains.com
*/

// If this file is called directly, abort. //
if ( ! defined( 'WPINC' ) ) {die;} // end if

// Let's Initialize Everything
if ( file_exists( plugin_dir_path( __FILE__ ) . 'core-init.php' ) ) {
require_once( plugin_dir_path( __FILE__ ) . 'core-init.php' );
}
